version: "3.7"
services:
  airflow:
    build: ../../docker
    image: manning-airflow:latest
    ports:
      - "127.0.0.1:8085:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
  postgres:
    build: insideairbnb
    ports:
      - "127.0.0.1:8085:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags

networks:
  airflow:
